### ISSUE TITLE
Help Wanted: Make the boxes in the fitness wiki match nutrition wiki

### ISSUE THREAD

**Issue by BrianFrancisDG** [BrianFrancisDG/Swole-Goal#75]
http://swolegoal.azurewebsites.net/Home/FitnessWiki

has gray boxes for the descriptions of things. We were wondering what it would look like if it had the same black boxes as the Nutrition wiki. http://swolegoal.azurewebsites.net/Home/NutritionWiki

Our task for you is to match the style of the Fitness Wiki boxes to be the same as the Nutrition Wiki boxes

When you make a branch name it **'HW-Issue-Fix-75'**

**Comment by sriram1996** [comment]
Hey guys I have been assigned to your task, looks like an awesome app and looking forward to working with you! I will contact you soon for any questions pertaining to the issue.
