### ISSUE TITLE
I am a 41 year old trying to get swole.

### ISSUE THREAD

**Issue by brylee123** [BrianFrancisDG/Swole-Goal#85]
I demand a reason why there is no option for me and my 41-year-old body.

![image](https://user-images.githubusercontent.com/22011502/31964629-ac278726-b8d2-11e7-81a1-233493520e77.png)

**Comment by valenciak** [comment]
This is intentional. We like to stay on the safer side of things and provide information for individuals up to the age of 40. If you are older than 40 and would like to use our site just select 40 as your age.
