### ISSUE TITLE
Bug: Title overlap on fullscreen

### ISSUE THREAD

**Issue by zsmoore** [BrianFrancisDG/Swole-Goal#88]
![overlap](https://user-images.githubusercontent.com/8812688/32359259-1ad7cdd2-c023-11e7-80dd-56f709364904.png)
![non-overlap](https://user-images.githubusercontent.com/8812688/32359264-2360943e-c023-11e7-820e-3970e9ac2b2b.png)
Looks like your main title overlaps the about when I am using fullscreen on my laptop.
Second picture is when I go half screen

Resolution is 1920 x 1080

**Comment by BrianFrancisDG** [comment]
@zsmoore We can't seem to recreate the bug.  

![image](https://user-images.githubusercontent.com/24644293/32425276-ecbacd6e-c27f-11e7-8b97-791bcd94acf7.png)
