### ISSUE TITLE
Bug: Navbar on Nutrition wiki goes to wrong location

### ISSUE THREAD

**Issue by zsmoore** [BrianFrancisDG/Swole-Goal#89]
When clicking on the `Contact` button from the Navbar while on the Nutrition Wiki, I end up getting redirected to the About page on the main website.

**Comment by zsmoore** [comment]
Looks like this has already been referenced in #86 .  Feel free to close

**Comment by BrianFrancisDG** [comment]
This should be fixed now! Thank you so much using our app!
