### ISSUE TITLE
This website isn't secure.

### ISSUE THREAD

**Issue by QinxinTian** [BrianFrancisDG/Swole-Goal#98]
<img width="768" alt="2017-11-06 7 12 58" src="https://user-images.githubusercontent.com/25886116/32440624-00bbdf32-c2c2-11e7-8cb4-aa2db93c491e.png">
If this is secure, the left hand side of the address should be green.

**Comment by valenciak** [comment]
Our website isn't storing any user data therefor there isn't a need for it to be secure.
